# Generated by Django 5.0.6 on 2024-08-21 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0002_alter_blog_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='status',
            field=models.CharField(choices=[('publish', 'Publish'), ('draft', 'Draft'), ('hidden', 'Hidden')], default='draft', max_length=10),
        ),
        migrations.AddField(
            model_name='comment',
            name='status',
            field=models.CharField(choices=[('show', 'Show'), ('hidden', 'Hidden')], default='show', max_length=10),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
