# Generated by Django 5.0.6 on 2024-10-05 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userpanel', '0005_blog_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='author',
        ),
    ]
