# Generated by Django 5.0.6 on 2024-10-08 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userpanel', '0007_blog_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileuser',
            name='profile_image',
            field=models.ImageField(upload_to='profile/'),
        ),
    ]
